tas:
  - name: Mark
  - name: Rachit
  - name: Yuntian

dates: ["", "Aug. 30", "Sep. 1", "Sep. 6", "Sep. 8", "Sep. 11", "Sep. 13", "Sep. 15", "Sep. 18","Sep. 20", "Sep. 22", "Sep. 25.", "Sep. 27.", "Sep. 29.", "Oct. 2", "Oct. 4", "Oct. 6", "Oct. 11", "Oct. 13", "Oct. 16", "Oct. 18", "Oct. 20", "Oct. 23", "Oct. 25", "Oct. 27", "Oct. 30", "Nov. 1","Nov. 3", "Nov. 6", "Nov. 8",  "Nov. 10", "Nov. 13", "Nov. 15","Nov. 17" , "Nov. 20", "Nov. 22", "Nov. 27", "Nov. 29", "Dec. 1"]
ohs:
  - time: TBD Time
    location: TBD Place

lectures:
  - topic: Advanced Machine Learning
    subtopic:
    hw:
    papers:
    section:
    demos:
  - topic:
    subtopic: <a href="https://github.com/harvard-ml-courses/cs281-sections">Math Review</a>
    hw:
    papers:
    section:
    demos:
    active: 'active'
  - topic: Fundamentals
    subtopic: Discrete Models
    hw: T0 <a href="https://harvard-ml-courses.github.io/cs281-f17-homework/h1/homework0-regression.pdf">Warm-up</a> (<a href="https://canvas.harvard.edu/courses/29707/assignments/161722">submit</a> | <a href="">self-grading</a>)
    papers: 2.3, 3.3-4
    section:
    demos: <a href="https://github.com/harvard-ml-courses/cs281-demos/blob/master/beta.ipynb">Beta</a>
  - topic:
    subtopic:  Code Review
    hw:
    papers:
    section:
    demos:
    active: 'active'

  - topic:
    subtopic: Gaussian Models
    hw:
    papers: 2.4, 4.1, 4.3, 4.6
    section:
    demos:
  - topic:
    subtopic: Linear Regression
    hw:
    papers: 7.1-7.3, 7.6
    section:
    demos: <a href="https://github.com/harvard-ml-courses/cs281-demos/blob/master/Regression.ipynb">Beta</a>
  - topic:
    subtopic: Bayesian Methods
    hw:
    papers:
    section:
    demos:
    active: 'active'

  - topic:
    subtopic: Linear Classification
    hw: T1 <a href="https://harvard-ml-courses.github.io/cs281-f17-homework/h1/homework1-fundamentals.pdf">Fundamentals</a> (<a href="">submit</a> | <a href="">self-grading</a>)
    papers: 3.5
    section:
    demos:

  - topic: Graphical Models
    subtopic:  Exponential Families
    hw:
    papers:  9.1-3
    section:
    demos:
  - topic:
    subtopic: Optimization
    hw:
    papers:
    section:
    demos:
    active: 'active'
  - topic:
    subtopic: Neural Networks
    hw:
    papers: 16.5
    section:
    demos:
  - topic:
    subtopic: Directed Graphical Models
    hw:
    papers: 10.1, 10.2, 10.5
    section:
    demos:
  - topic:
    subtopic: Graphical Models
    hw:
    papers:
    section:
    demos:
    active: 'active'
  - topic:
    subtopic: Undirected Graphical Models
    hw:
    papers: 19.1-3
    section:
    demos:
  - topic: Exact Inference
    subtopic:  Time-Series Models
    hw: T2 <a href="https://harvard-ml-courses.github.io/cs281-f17-homework/h2/homework2-classification.pdf">Models</a> (<a href="https://canvas.harvard.edu/courses/21992/assignments/117078">submit</a> |  <a href="https://canvas.harvard.edu/courses/21992/quizzes/55050">self-grading</a>)
    papers: 17.4, 18.1, 18.3
    section:
    demos:
  - topic:
    subtopic:  Belief Propagation
    hw: FINAL PROJECT PROPOSALS DUE.
    papers: 20.1-3
    section:
    demos:
  - topic:
    subtopic: Exact Inference
    hw:
    papers:
    section:
    demos:
    active: 'active'
  - topic:
    subtopic: Recurrent Neural Networks
    hw:
    papers: (Deep Learning Chapter)
    section:
    demos:

  - topic: Approximate Inference
    subtopic: Information Theory
    hw:
    papers: 2.8
    section:
    demos:
  - topic:
    subtopic: Projects
    hw:
    papers:
    section:
    demos:
    active: 'active'
  - topic:
    subtopic: Midterm
    hw:
    papers: 
    section:
    demos:
  - topic: Variational Inference
    subtopic:  Mixture Models
    hw:
    papers: 11.1, 11.2, 11.4
    section:
    demos:
  - topic:
    subtopic: Midterm Review
    hw:
    papers:
    section:
    demos:
    active: 'active'
  - topic:
    subtopic: Mean Field
    hw: T3 <a href="https://harvard-ml-courses.github.io/cs281-f17-homework/h2/homework2-classification.pdf">Inference</a> (<a href="https://canvas.harvard.edu/courses/21992/assignments/117078">submit</a> |  <a href="https://canvas.harvard.edu/courses/21992/quizzes/55050">self-grading</a>)
    papers: 21.1-21.3
    section: 
    demos:
  - topic:
    subtopic: Advanced Variational Inference
    hw:
    papers: 21.6, 22.2
    section:
    demos:
  - topic:
    subtopic: Variational Methods
    hw:
    papers:
    section:
    demos:
    active: 'active'
  - topic:
    subtopic: MAP and Relaxations
    hw:
    papers: 22.6
    section:
    demos:
  - topic: Sampling-Based Inference
    subtopic:   Monte Carlo Basics
    hw:
    papers: 2.7, 23.1-3
    section:
    demos:
  - topic:
    subtopic: Sampling
    hw:
    papers:
    section:
    demos:
    active: 'active'
  - topic:
    subtopic: Importance Sampling and Particle Filtering
    hw:
    papers: 23.4-23.5
    section:
    demos:

  - topic:
    subtopic: Gibbs Sampling and MCMC
    hw:
    papers: 24.1-24.4
    section:
    demos:
  - topic:
    subtopic: Practical MCMC
    hw:
    papers:
    section:
    demos:
    active: 'active'
  - topic:  Deep Learning
    subtopic: Neural Networks
    hw: T4 <a href="https://github.com/harvard-ml-courses/cs281-f17-homework/tree/master/h5">Approximations</a> (<a href="">submit</a>)
    papers: 16.5
    section:
    demos:
  - topic:
    subtopic: Convolutional and Recurrent Networks
    hw:
    papers: (Deep Learning Chapter)
    section:
    demos:
  - topic:
    subtopic: Coding Neural Networks
    hw:
    papers:
    section:
    demos:
    active: 'active'

  - topic:
    subtopic: Deep Learning in Health Care (Guest Lecture)
    hw:
    papers:
    section:
    demos:
  - topic: DL Topics
    subtopic: Attention and Memory Models
    hw:
    papers: Attention, Memory Networks
    section:
    demos:
  - topic:
    subtopic: "Variational Autoencoders"
    hw:
    papers: VAE
    section:
    demos:
  - topic:
    subtopic: Applications
    hw:
    papers:
    section:
    demos:

  - topic:
    subtopic: Projects
    hw:
    papers:
    section:
    demos:
